# backend/.air.toml
root = "."
tmp_dir = "tmp"

[build]
# build command â€” keep same path you use in prod (./cmd/evaultz)
cmd = "go build -o ./tmp/evaultz ./cmd/evaultz"
bin = "tmp/evaultz"
full_bin = "tmp/evaultz"
