# .air.toml
root = "."
tmp_dir = "tmp"

[build]
# build command â€” note the "./cmd/evaultz"
cmd = "go build -o /app/tmp/main /app/cmd/evaultz"
bin = "/app/tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]
delay = 1000

[log]
time = true
color = true

[misc]
clean_on_exit = true
